"""Development-only demo data seeder for WhatsApp Raven Bridge."""

from __future__ import annotations

import os
from contextlib import contextmanager
from datetime import timedelta

import frappe
from frappe import _
from frappe.utils import cint, cstr, now_datetime
from frappe.utils.password import set_encrypted_password

from whatsapp_raven_bridge.bridge.account_route import ensure_route_memberships, get_or_create_inbox_channel
from whatsapp_raven_bridge.bridge.backfill import backfill_whatsapp_messages
from whatsapp_raven_bridge.bridge.conversation import create_message_link, get_or_create_conversation
from whatsapp_raven_bridge.bridge.raven_destination import ensure_raven_destination
from whatsapp_raven_bridge.utils.settings import get_settings

DEMO_ACCOUNT_NAME = "WRB Demo WhatsApp Account"
DEMO_ROUTE_PREFIX = "whatsapp-inbox-wrb-demo"
DEMO_MESSAGE_ID_PREFIX = "wamid.wrb.demo."
DEMO_PHONE_PREFIX = "4478709009"
DEMO_SOURCE = "whatsapp_raven_bridge_demo_seed"
DEMO_TOPICS = [
	"Sales inquiry",
	"Support issue",
	"Booking request",
	"Payment question",
	"Delivery update",
	"Refund request",
	"Product question",
	"Complaint",
	"Follow-up",
	"General chat",
]


def _is_safe_dev_site() -> bool:
	site = cstr(getattr(frappe.local, "site", "") or "").lower()
	return any(token in site for token in ("dev", "development", "local", "test"))


def _assert_dev_seed_allowed(force: int = 0):
	if cint(frappe.conf.get("developer_mode")):
		return
	if cstr(os.environ.get("WHATSAPP_RAVEN_BRIDGE_ALLOW_DEMO_SEED") or "").strip() == "1":
		return
	if cint(force) and _is_safe_dev_site():
		return
	frappe.throw(
		_(
			"Demo seeding is development-only. Enable developer_mode, set WHATSAPP_RAVEN_BRIDGE_ALLOW_DEMO_SEED=1, "
			"or pass force=1 on a development/local/test site."
		)
	)


@contextmanager
def _patched_whatsapp_notify():
	from frappe_whatsapp.frappe_whatsapp.doctype.whatsapp_message.whatsapp_message import WhatsAppMessage

	original_notify = WhatsAppMessage.notify

	def fake_notify(doc, data):
		if not doc.message_id:
			doc.message_id = f"{DEMO_MESSAGE_ID_PREFIX}{frappe.generate_hash(length=10)}"
		doc.status = "Success"
		return {"messages": [{"id": doc.message_id}]}

	WhatsAppMessage.notify = fake_notify
	try:
		yield
	finally:
		WhatsAppMessage.notify = original_notify


def _ensure_demo_account() -> str:
	if not frappe.db.exists("WhatsApp Account", DEMO_ACCOUNT_NAME):
		frappe.get_doc(
			{
				"doctype": "WhatsApp Account",
				"account_name": DEMO_ACCOUNT_NAME,
				"status": "Active",
				"url": "https://graph.facebook.com",
				"version": "v17.0",
				"phone_id": "wrb_demo_phone_id",
				"business_id": "wrb_demo_business_id",
				"app_id": "wrb_demo_app_id",
				"webhook_verify_token": "wrb_demo_verify_token",
			}
		).insert(ignore_permissions=True)
	set_encrypted_password("WhatsApp Account", DEMO_ACCOUNT_NAME, "wrb-demo-token", "token")
	return DEMO_ACCOUNT_NAME


def _ensure_demo_route(workspace: str) -> str:
	existing = frappe.db.get_value(
		"WhatsApp Raven Account Route",
		{"whatsapp_account": DEMO_ACCOUNT_NAME, "enabled": 1},
		"name",
	)
	if existing:
		route = frappe.get_doc("WhatsApp Raven Account Route", existing)
		route.raven_workspace = workspace
		route.channel_type = "Private"
		route.conversation_strategy = "Thread Per Contact"
		route.allow_unassigned_reply = 0
		if not any(cstr(row.raven_user) == "Administrator" for row in (route.members or [])):
			route.append("members", {"raven_user": "Administrator", "is_admin": 1, "can_reply": 1})
		route.save(ignore_permissions=True)
	else:
		route = frappe.get_doc(
			{
				"doctype": "WhatsApp Raven Account Route",
				"enabled": 1,
				"whatsapp_account": DEMO_ACCOUNT_NAME,
				"raven_workspace": workspace,
				"inbox_channel_name": DEMO_ROUTE_PREFIX,
				"channel_type": "Private",
				"conversation_strategy": "Thread Per Contact",
				"allow_unassigned_reply": 0,
				"members": [{"raven_user": "Administrator", "is_admin": 1, "can_reply": 1}],
				"notes": "Auto-generated by whatsapp_raven_bridge demo seeder",
			}
		).insert(ignore_permissions=True)
	get_or_create_inbox_channel(route)
	ensure_route_memberships(route)
	return route.name


def _ensure_bridge_settings():
	settings = get_settings()
	if not settings:
		settings = frappe.get_single("WhatsApp Raven Bridge Settings")
	settings.enabled = 1
	settings.enable_outbound_replies = 1
	if not settings.default_raven_workspace:
		settings.default_raven_workspace = "Raven"
	if not settings.default_channel_type:
		settings.default_channel_type = "Private"
	if not settings.conversation_strategy:
		settings.conversation_strategy = "Thread Per Contact"
	settings.save(ignore_permissions=True)
	return settings


def _set_doc_timestamp(doctype: str, name: str, dt):
	frappe.db.sql(
		f"update `tab{doctype}` set creation=%s, modified=%s where name=%s",
		(dt, dt, name),
	)
	frappe.clear_document_cache(doctype, name)


def _delete_demo_seed_data():
	for name in frappe.get_all(
		"WhatsApp Raven Message Link",
		filters=[["whatsapp_message_id", "like", f"{DEMO_MESSAGE_ID_PREFIX}%"]],
		pluck="name",
	):
		if frappe.db.exists("WhatsApp Raven Message Link", name):
			frappe.delete_doc("WhatsApp Raven Message Link", name, force=True)

	for name in frappe.get_all(
		"WhatsApp Message",
		filters=[["message_id", "like", f"{DEMO_MESSAGE_ID_PREFIX}%"]],
		pluck="name",
	):
		if frappe.db.exists("WhatsApp Message", name):
			frappe.delete_doc("WhatsApp Message", name, force=True)

	for name in frappe.get_all(
		"WhatsApp Raven Conversation",
		filters=[["phone_number", "like", f"{DEMO_PHONE_PREFIX}%"]],
		pluck="name",
	):
		if frappe.db.exists("WhatsApp Raven Conversation", name):
			frappe.delete_doc("WhatsApp Raven Conversation", name, force=True)


@frappe.whitelist()
def create_demo_whatsapp_raven_data(
	conversations: int = 10,
	messages_per_conversation: int = 10,
	cleanup_existing: int = 0,
	force: int = 0,
):
	"""Create local demo data for WhatsApp-Raven UI testing without real Meta sends."""
	_assert_dev_seed_allowed(force=force)
	if frappe.session.user != "Administrator":
		frappe.only_for("System Manager")

	conversations = max(1, min(int(conversations or 10), 50))
	messages_per_conversation = max(1, min(int(messages_per_conversation or 10), 50))

	if cint(cleanup_existing):
		_delete_demo_seed_data()

	settings = _ensure_bridge_settings()
	workspace = cstr(settings.default_raven_workspace or "Raven")
	_ensure_demo_account()
	_ensure_demo_route(workspace)

	summary = {
		"seeded_conversations": 0,
		"seeded_messages": 0,
		"incoming_live": 0,
		"outgoing_imported": 0,
		"human_replies": 0,
		"conversation_names": [],
		"source": DEMO_SOURCE,
	}
	base_ts = now_datetime() - timedelta(days=7)

	with _patched_whatsapp_notify():
		for idx in range(conversations):
			purpose = DEMO_TOPICS[idx % len(DEMO_TOPICS)]
			phone = f"{DEMO_PHONE_PREFIX}{idx:02d}"
			profile_name = f"Demo {purpose}"
			conversation = get_or_create_conversation(
				phone,
				whatsapp_account=DEMO_ACCOUNT_NAME,
				profile_name=profile_name,
			)
			ensure_raven_destination(conversation)
			conversation.reload()
			summary["seeded_conversations"] += 1
			summary["conversation_names"].append(conversation.name)

			for m_idx in range(messages_per_conversation):
				ts = base_ts + timedelta(minutes=(idx * 100) + m_idx)
				message_id = f"{DEMO_MESSAGE_ID_PREFIX}{idx:02d}.{m_idx:02d}"
				body = f"[{purpose}] demo message {m_idx + 1}"
				slot = m_idx % 3

				if slot == 0:
					if frappe.db.exists("WhatsApp Message", {"message_id": message_id}):
						continue
					incoming = frappe.get_doc(
						{
							"doctype": "WhatsApp Message",
							"type": "Incoming",
							"content_type": "text",
							"message_type": "Manual",
							"from": phone,
							"profile_name": profile_name,
							"message": body,
							"message_id": message_id,
							"whatsapp_account": DEMO_ACCOUNT_NAME,
						}
					).insert(ignore_permissions=True)
					_set_doc_timestamp("WhatsApp Message", incoming.name, ts)
					link_name = frappe.db.get_value("WhatsApp Raven Message Link", {"whatsapp_message": incoming.name}, "name")
					if link_name:
						raven_name = frappe.db.get_value("WhatsApp Raven Message Link", link_name, "raven_message")
						if raven_name and frappe.db.exists("Raven Message", raven_name):
							_set_doc_timestamp("Raven Message", raven_name, ts)
					summary["incoming_live"] += 1
					summary["seeded_messages"] += 1
					continue

				if slot == 1:
					if frappe.db.exists("WhatsApp Message", {"message_id": message_id}):
						continue
					outgoing = frappe.get_doc(
						{
							"doctype": "WhatsApp Message",
							"type": "Outgoing",
							"content_type": "text",
							"message_type": "Manual",
							"to": phone,
							"message": body,
							"message_id": message_id,
							"status": "Success",
							"whatsapp_account": DEMO_ACCOUNT_NAME,
						}
					).insert(ignore_permissions=True)
					_set_doc_timestamp("WhatsApp Message", outgoing.name, ts)
					summary["outgoing_imported"] += 1
					summary["seeded_messages"] += 1
					continue

				previous_syncing = getattr(frappe.flags, "whatsapp_raven_bridge_syncing", False)
				try:
					frappe.flags.whatsapp_raven_bridge_syncing = True
					raven_message = frappe.get_doc(
						{
							"doctype": "Raven Message",
							"channel_id": conversation.raven_channel,
							"message_type": "Text",
							"text": f"<p>{frappe.utils.escape_html(body)} (agent)</p>",
							"is_bot_message": 0,
							"json": {"source": DEMO_SOURCE, "purpose": "demo_human_reply"},
						}
					).insert(ignore_permissions=True)
				finally:
					frappe.flags.whatsapp_raven_bridge_syncing = previous_syncing

				_set_doc_timestamp("Raven Message", raven_message.name, ts)
				outgoing = frappe.get_doc(
					{
						"doctype": "WhatsApp Message",
						"type": "Outgoing",
						"content_type": "text",
						"message_type": "Manual",
						"to": phone,
						"message": body,
						"message_id": message_id,
						"status": "Success",
						"whatsapp_account": DEMO_ACCOUNT_NAME,
						"reference_doctype": "Raven Message",
						"reference_name": raven_message.name,
					}
				).insert(ignore_permissions=True)
				_set_doc_timestamp("WhatsApp Message", outgoing.name, ts)
				create_message_link(
					whatsapp_message=outgoing.name,
					raven_message=raven_message.name,
					conversation=conversation.name,
					whatsapp_message_id=outgoing.message_id,
					direction="Outgoing",
					metadata={
						"source": DEMO_SOURCE,
						"direction": "outgoing",
						"purpose": "demo_human_reply",
					},
					raven_channel=conversation.raven_channel,
				)
				summary["human_replies"] += 1
				summary["seeded_messages"] += 1

			backfill_whatsapp_messages(
				whatsapp_account=DEMO_ACCOUNT_NAME,
				phone_number=phone,
				direction="Outgoing",
				limit=messages_per_conversation * 3,
				dry_run=0,
				preserve_raven_timestamps=1,
				scheduled=0,
			)

	return summary
